[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
blip_radar = "BvD8LJS8jmoRoGchwvJs5hbJhdMAYg8hcA4H7wr4jBdy"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
